### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by MRodneyMcKay** [IBCNServices/easy-openvpn-server#2]
I get this error massage when i try to install the snap package.

# sudo snap install easy-openvpn-server --candidate 
error: cannot perform the following tasks:
- Run configure hook of "easy-openvpn-server" snap if present (run hook "configure": 
-----
RUNNING configure hook
INFO: Generating config for vpn daemons.
Traceback (most recent call last):
  File "/snap/easy-openvpn-server/78/bin/setup.py", line 724, in <module>
    cli() #pylint: disable=E1123,E1120
  File "/snap/easy-openvpn-server/78/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/snap/easy-openvpn-server/78/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/snap/easy-openvpn-server/78/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/snap/easy-openvpn-server/78/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/easy-openvpn-server/78/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/snap/easy-openvpn-server/78/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/snap/easy-openvpn-server/78/bin/setup.py", line 654, in setup
    create_server_config(ctx.obj["result_dir"], ctx.obj["status_dir"])
  File "/snap/easy-openvpn-server/78/bin/setup.py", line 494, in create_server_config
    dns_info = get_dns_info()
  File "/snap/easy-openvpn-server/78/bin/setup.py", line 319, in get_dns_info
    ns_address = IPv4Address(ns_address)
  File "/snap/easy-openvpn-server/78/usr/lib/python3.6/ipaddress.py", line 1284, in __init__
    self._ip = self._ip_int_from_string(addr_str)
  File "/snap/easy-openvpn-server/78/usr/lib/python3.6/ipaddress.py", line 1118, in _ip_int_from_string
    raise AddressValueError("Expected 4 octets in %r" % ip_str)
ipaddress.AddressValueError: Expected 4 octets in 'fe80::1%enp7s0'
-----)

**Comment by oncer** [comment]
I have the same issue

**Comment by Mikhael-Danilov** [comment]
Same issue on ubuntu 18.04:

```
error: cannot perform the following tasks:
- Run configure hook of "easy-openvpn-server" snap if present (run hook "configure": 
-----
RUNNING configure hook
INFO: Generating config for vpn daemons.
Traceback (most recent call last):
  File "/snap/easy-openvpn-server/121/bin/setup.py", line 840, in <module>
    cli() #pylint: disable=E1123,E1120
  File "/snap/easy-openvpn-server/121/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/snap/easy-openvpn-server/121/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/snap/easy-openvpn-server/121/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/snap/easy-openvpn-server/121/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/easy-openvpn-server/121/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/snap/easy-openvpn-server/121/lib/python3.6/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/snap/easy-openvpn-server/121/bin/setup.py", line 769, in setup
    create_server_config(ctx.obj["result_dir"], ctx.obj["status_dir"])
  File "/snap/easy-openvpn-server/121/bin/setup.py", line 585, in create_server_config
    dns_info = get_dns_info()
  File "/snap/easy-openvpn-server/121/bin/setup.py", line 406, in get_dns_info
    ns_address = IPv4Address(ns_address)
  File "/snap/easy-openvpn-server/121/usr/lib/python3.6/ipaddress.py", line 1284, in __init__
    self._ip = self._ip_int_from_string(addr_str)
  File "/snap/easy-openvpn-server/121/usr/lib/python3.6/ipaddress.py", line 1118, in _ip_int_from_string
    raise AddressValueError("Expected 4 octets in %r" % ip_str)
ipaddress.AddressValueError: Expected 4 octets in '2001:4860:4860::8844'

```

**Comment by ejnu** [comment]
the same here.. any fix for that?
